import type {ReactNode} from 'react';
import {AlertCircle, ArrowUpRight, Check, Inbox, LoaderCircle, X} from 'lucide-react';
import {humanize} from './Fields';
export function Badge({value}: {value:string}) {const tone=['implemented','published','approved','active','complete','completed','done','ready','pass','keep','available','accepted'].includes(value)?'green':['expired','rejected','blocked','fail','critical','urgent','revoke'].includes(value)?'red':['in_progress','in_review','treating','assessing','submitted','medium','high','pending','intake'].includes(value)?'amber':'neutral';return <span className={`badge badge-${tone}`}><span className="status-dot"/>{humanize(value || 'Not set')}</span>;}
export function Loading({label='Loading workspace…'}:{label?:string}) {return <div className="loading" role="status"><LoaderCircle size={20} className="spin"/>{label}</div>;}
export function ErrorState({message,retry}:{message:string;retry?:()=>void}) {return <div className="error-state" role="alert"><AlertCircle size={20}/><div><strong>Something needs your attention</strong><p>{message}</p>{retry&&<button className="button" onClick={retry}>Try again</button>}</div></div>;}
export function EmptyState({title,description,action}:{title:string;description:string;action?:ReactNode}) {return <div className="empty-state"><span className="empty-icon"><Inbox size={24}/></span><h3>{title}</h3><p>{description}</p>{action}</div>;}
export function PageHeader({eyebrow='OPERATE',title,description,children}:{eyebrow?:string;title:string;description:string;children?:ReactNode}) {return <header className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div><div className="header-actions">{children}</div></header>;}
export function Note({children}:{children:ReactNode}) {return <div className="note"><span className="note-mark">i</span><div>{children}</div></div>;}
export function Metric({label,value,detail}:{label:string;value:ReactNode;detail?:string}) {return <div className="metric"><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>;}
export function Toast({message,kind,onClose}:{message:string;kind:'success'|'error';onClose:()=>void}) {return <div className={`toast toast-${kind}`} role={kind==='error'?'alert':'status'}>{kind==='error'?<AlertCircle size={18}/>:<Check size={18}/>}<span>{message}</span><button className="icon-button" aria-label="Dismiss notification" onClick={onClose}><X size={16}/></button></div>;}
export function ExternalHint() {return <ArrowUpRight size={14}/>;}
export function formatDate(value?:string|null) { if(!value)return '—'; const date=new Date(value.length===10?`${value}T12:00:00`:value); return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric'}).format(date); }
